#! /usr/bin/env python

import atexit
import os
import readline
import rlcompleter
import sys

# Enable tab completion
readline.parse_and_bind("tab: complete")

# Enable cross-session history
history_file = os.path.expanduser('~/.python_history')
if os.path.exists(history_file):
    readline.read_history_file(history_file)
atexit.register(readline.write_history_file, history_file)

# Clean up the evidence
del history_file
del atexit
del os
del readline
del rlcompleter
del sys

# Reset __vars__ to default, for transparency of rc file.
try:
    del __file__
    __doc__ = None
except NameError:
    pass
