#! /usr/bin/env python

""" If the PYTHONSTARTUP environment variable points to this file, the below
commands are executed before the first prompt is displayed in interactive mode.
This happens in the same namespace where interactive commands are executed, so
the objects defined or imported here can be used without qualification in the
interactive session. """

import atexit
import os
import readline
import rlcompleter
import sys

# Enable tab completion
readline.parse_and_bind("tab: complete")

# Enable cross-session history
history_file = os.path.expanduser('~/.python_history')
if os.path.exists(history_file):
    readline.read_history_file(history_file)
atexit.register(readline.write_history_file, history_file)

# Clean up the evidence
del history_file
del atexit
del os
del readline
del rlcompleter
del sys

# Reset __vars__ to default, for transparency of rc file.
try:
    del __file__
    __doc__ = None
except NameError:
    pass
